ALTER TABLE schema_auth.users
  ADD COLUMN IF NOT EXISTS department VARCHAR(100) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS squad VARCHAR(100) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS grade VARCHAR(50) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS profile_completed BOOLEAN NOT NULL DEFAULT false;
