param(
  [switch]$PostCommit,
  [string]$Category = "chore",
  [string]$Title = "",
  [string]$Scope = "project",
  [switch]$DryRun
)

$ErrorActionPreference = "Stop"

function Invoke-Git {
  param([Parameter(ValueFromRemainingArguments = $true)][string[]]$Args)
  $output = & git @Args 2>$null
  if ($LASTEXITCODE -ne 0) { return "" }
  return ($output -join "`n").Trim()
}

function New-Slug {
  param([string]$Text)
  $slug = $Text.ToLowerInvariant()
  $slug = [regex]::Replace($slug, "[^a-z0-9]+", "-").Trim("-")
  if ($slug.Length -gt 48) { $slug = $slug.Substring(0, 48).Trim("-") }
  if ([string]::IsNullOrWhiteSpace($slug)) { return "dev-record" }
  return $slug
}

function Escape-MarkdownCell {
  param([string]$Text)
  return ($Text -replace "\|", "\|").Trim()
}

try {
  $repoRoot = Invoke-Git rev-parse --show-toplevel
  if ([string]::IsNullOrWhiteSpace($repoRoot)) {
    Write-Host "dev-record skipped: not inside a git repository."
    exit 0
  }

  Set-Location $repoRoot

  $recordsDir = Join-Path $repoRoot "docs/dev-records"
  $entriesDir = Join-Path $recordsDir "entries"
  $timelinePath = Join-Path $recordsDir "timeline.md"
  New-Item -ItemType Directory -Force -Path $entriesDir | Out-Null

  $commit = Invoke-Git rev-parse --short HEAD
  if ([string]::IsNullOrWhiteSpace($commit)) {
    Write-Host "dev-record skipped: no HEAD commit."
    exit 0
  }

  $subject = Invoke-Git log -1 --pretty=%s
  if (-not [string]::IsNullOrWhiteSpace($Title)) { $subject = $Title }
  if ([string]::IsNullOrWhiteSpace($subject)) { $subject = "Untitled change" }

  $branch = Invoke-Git branch --show-current
  if ([string]::IsNullOrWhiteSpace($branch)) { $branch = "detached" }

  $now = Get-Date
  $time = $now.ToString("yyyy-MM-dd HH:mm:ss zzz")
  $timelineTime = $now.ToString("yyyy-MM-dd HH:mm")
  $stamp = $now.ToString("yyyy-MM-dd-HHmmss")
  $slug = New-Slug $subject
  $entryName = "$stamp-$slug.md"
  $entryPath = Join-Path $entriesDir $entryName

  $existing = Get-ChildItem -Path $entriesDir -Filter "*.md" -ErrorAction SilentlyContinue |
    Select-String -Pattern "Commit:\s+$commit" -SimpleMatch:$false |
    Select-Object -First 1
  if ($existing) {
    Write-Host "dev-record skipped: commit $commit already recorded."
    exit 0
  }

  $stat = Invoke-Git show --stat --oneline --no-renames --format=short HEAD
  if ([string]::IsNullOrWhiteSpace($stat)) { $stat = "(no stat available)" }

  $status = Invoke-Git status --short
  if ([string]::IsNullOrWhiteSpace($status)) { $status = "(clean)" }

  $entryLines = @(
    "# $subject",
    "",
    "- Time: $time",
    "- Category: $Category",
    "- Branch: $branch",
    "- Commit: $commit",
    "- Scope: $Scope",
    "- Generated by: scripts/dev-record.ps1",
    "",
    "## Context",
    "",
    "Record the user request, decision context, and why this change was needed.",
    "",
    "## Outcome",
    "",
    "Record what changed and how the result was validated.",
    "",
    "## Follow-ups",
    "",
    "- None yet.",
    "",
    "## Key Changes",
    "",
    "~~~text",
    $stat,
    "~~~",
    "",
    "## Working Tree After Commit",
    "",
    "~~~text",
    $status,
    "~~~"
  )
  $entry = $entryLines -join "`n"

  if ($DryRun) {
    Write-Host $entry
    exit 0
  }

  Set-Content -Path $entryPath -Value $entry -Encoding UTF8

  if (-not (Test-Path $timelinePath)) {
    $initialTimeline = New-Object System.Collections.Generic.List[string]
    $initialTimeline.Add("# Development Timeline")
    $initialTimeline.Add("")
    $initialTimeline.Add("> This file is appended by scripts/dev-record.ps1. Important milestones can also be added manually.")
    $initialTimeline.Add("")
    $initialTimeline.Add("| Time | Type | Title | Branch | Commit | Record |")
    $initialTimeline.Add("|------|------|------|------|------|------|")
    Set-Content -Path $timelinePath -Value $initialTimeline -Encoding UTF8
  }

  $timeline = Get-Content -Path $timelinePath -Raw -Encoding UTF8
  if ($timeline -notmatch [regex]::Escape($commit)) {
    $safeTitle = Escape-MarkdownCell $subject
    $safeCategory = Escape-MarkdownCell $Category
    $safeBranch = Escape-MarkdownCell $branch
    Add-Content -Path $timelinePath -Encoding UTF8 -Value "| $timelineTime | $safeCategory | $safeTitle | $safeBranch | $commit | [$entryName](entries/$entryName) |"
  }

  Write-Host "dev-record wrote docs/dev-records/entries/$entryName"
  exit 0
} catch {
  Write-Host "dev-record skipped: $($_.Exception.Message)"
  exit 0
}
